
name: CI

on:

  pull_request:
     types: [ labeled ]

jobs:
  test:
    if: github.event.label.name == 'skip-tests' 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Test jobs
        run: echo 'Smoke tests'