name: Smoke environment deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
   runs-on: ubuntu-latest
   outputs:
      output1: ${{ github.event.head_commit.message }}
   steps:
      - uses: actions/checkout@v3
      - name: Deploy job
        run: echo $GITHUB_OUTPUT
