name: Smoke environment deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
   runs-on: ubuntu-latest
   steps:
      - uses: actions/checkout@v3
      - name: Deploy job
        run: echo 'Run smoke deploy'
