
name: Smoke environment test

on:
  workflow_run:
    workflows: ["Smoke environment deploy"]
    types:
      - completed
  workflow_dispatch:

jobs:
  test: 
   if: ${{ github.event.workflow_run.conclusion == 'success' }}
   runs-on: ubuntu-latest
   steps:
      - uses: actions/checkout@v3
      - name: Test job
        run: |
          echo 'Simulate failed smoke tests!'
          exit 1

  skip-test:
    if: github.event_name == 'workflow_dispatch' 
    runs-on: ubuntu-latest
    steps:
      - name: Skip test job
        run: echo 'Skip smoke tests'